export const turkish = {
  app_name: 'Konuşarak Öğren',
  quiz: {
    top_title: "Quiz & Test",
    title: "Tüm Testler",
    description: "Konuşma paketinize ait testleri aşağıda bulabilir ve çözebilirsiniz.",
    answered_quiz: "Daha önce cevaplanan üniteler <span class=\"material-symbols-outlined text-primary\">check</span> işareti ile gösterilmektedir.",
    view_book: "Kitabı Görüntüle",
    show_report: "Sonucu Görüntüle",
    start: "Başla",
    remaining_time: "Kalan Süre",
    control: "Kontrol Et",
    continue: "Devam Et",
    quiz_completed: "Testi Tamamladınız",
    report_description: "Bu test ile ilgili ayrıntılı bilgiyi aşağıda bulabilirsiniz.",
    solve_again: "Testi Tekrar Başlat",
    start_time: "Başlangıç",
    end_time: "Bitiş",
    total_question: "Toplam soru",
    right_answer: "Doğru cevap",
    wrong_answer: "Yanlış cevap",
    empty_answer: "Boş bırakılan",
    timer_end_description: "Test süresiniz doldu. Test sonucunu görmek için aşağıdaki butona tıklayınız.",
    quit_modal_text: "Çıkış yapmanız durumunda çözmüş olduğunuz test yarım kalacaktır.\nÇıkış yapmak istediğinize emin misiniz?",
    quit: "Çıkış yap",
    want_continue: "Devam etmek istiyorum",
    leave_empty: "Boş Bırak",
    last_lesson: "Son Ders",
    show_result: "Sonucu Görüntüle"
  },
  turkish: 'Türkçe',
  english: 'English'
};
